### PR TITLE
some changes in Heading to make looks cool

### PR DESCRIPTION
**Pull request by Satya7390**

### CODE REVIEW

**Comment by Satya7390** [comment]
Changes in heading tag and added some CSS animations

**Comment by bacloud22** [comment]
Hi, image did not upload

**Comment by Satya7390** [comment]
Screenshot 2024-10-27 114132

**Comment by Satya7390** [comment]
> Hi, image did not upload

upload done

**Comment by bacloud22** [comment]
Please add small paddings by making groups:

```html
<div class="create-channel">
     <input>
     <button>
</div>

<div class="answer-question">
     <input>
     <button>
</div>
```

Can you ?

**Comment by Satya7390** [comment]
Yeah sure plz give me some time till tonight I will done .

**Comment by Satya7390** [comment]
I hope it will be helps you in your projects !!

**Review by bacloud22 — APPROVED** [review]

**Pull request merged**
